### ISSUE TITLE
是否多了个0？

### ISSUE THREAD

**Issue by 2016WUJI01** [lz1998/zbot#1]
https://github.com/lz1998/zbot/blob/f21878a3bbd95f9361be04c0d42bef1068fb6723/src/main/kotlin/net/lz1998/zbot/plugin/RepeatPlugin.kt#L26
这一行300是否应该改为30?

**Comment by lz1998** [comment]
> https://github.com/lz1998/zbot/blob/f21878a3bbd95f9361be04c0d42bef1068fb6723/src/main/kotlin/net/lz1998/zbot/plugin/RepeatPlugin.kt#L26
> 
> 
> 这一行300是否应该改为30?

后来改成5分钟了

**Comment by lz1998** [comment]
注释改掉了
