### ISSUE TITLE
群管

### ISSUE THREAD

**Issue by 2mf8** [lz1998/zbot#4]
禁言指令：
.ban <QQ>
踢人指令：
.t <QQ>
.T <QQ>
权限：群主、群管理员

**Comment by lz1998** [comment]
t小写：可以再次进群
T大写：禁止再次进群

**Comment by lz1998** [comment]
ban指令支持的时间单位：d天，h小时，m分钟，s秒
`.ban <QQ> 1d2h3m4s`
禁言QQ 1天2小时3分钟4秒，其中QQ可用@替代

或者其他格式，可以讨论下格式
